In [35]:
import numpy as np
import pandas as pd

In [36]:
# Load the csv into a pandas database
netflix = pd.read_csv('netflix_titles.csv', keep_default_na=False)
netflix.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,,,,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [37]:
# Remove director, cast, dated_added, and description columns 
# since we aren't going to be using them in our project.
netflix_cleaned = netflix.drop(columns=['director', 'cast', 'date_added', 'description'])
netflix_cleaned = netflix_cleaned[netflix_cleaned['country'] != '']
netflix_cleaned.head(5)

,show_id,type,title,country,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,United States,2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,South Africa,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
4,s5,TV Show,Kota Factory,India,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
7,s8,Movie,Sankofa,"United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
8,s9,TV Show,The Great British Baking Show,United Kingdom,2021,TV-14,9 Seasons,"British TV Shows, Reality TV"

In [40]:
# Sub-database holding just movies
netflix_movies = netflix_cleaned[netflix_cleaned['type'] == 'Movie']
netflix_movies

,show_id,type,title,country,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,United States,2020,PG-13,90 min,Documentaries
7,s8,Movie,Sankofa,"United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
9,s10,Movie,The Starling,United States,2021,PG-13,104 min,"Comedies, Dramas"
12,s13,Movie,Je Suis Karl,"Germany, Czech Republic",2021,TV-MA,127 min,"Dramas, International Movies"
24,s25,Movie,Jeans,India,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies"
...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,"United Arab Emirates, Jordan",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers"
8802,s8803,Movie,Zodiac,United States,2007,R,158 min,"Cult Movies, Dramas, Thrillers"
8804,s8805,Movie,Zombieland,United States,2009,R,88 min,"Comedies, Horror Movies"
8805,s8806,Movie,Zoom,United States,2006,PG,88 min,"Children & Family Movies, Comedies"
8806,s8807,Movie,Zubaan,India,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals"

In [39]:
# Sub-database holding just tv shows
netflix_shows = netflix_cleaned[netflix_cleaned['type'] == 'TV Show']
netflix_shows

,show_id,type,title,country,release_year,rating,duration,listed_in
1,s2,TV Show,Blood & Water,South Africa,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
4,s5,TV Show,Kota Factory,India,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
8,s9,TV Show,The Great British Baking Show,United Kingdom,2021,TV-14,9 Seasons,"British TV Shows, Reality TV"
15,s16,TV Show,Dear White People,United States,2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas"
17,s18,TV Show,Falsa identidad,Mexico,2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ..."
...,...,...,...,...,...,...,...,...
8780,s8781,TV Show,Yo-Kai Watch,United States,2015,TV-Y7,1 Season,"Anime Series, Kids' TV"
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,"Japan, Canada",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV"
8796,s8797,TV Show,Yunus Emre,Turkey,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8797,s8798,TV Show,Zak Storm,"United States, France, South Korea, Indonesia",2016,TV-Y7,3 Seasons,Kids' TV
8800,s8801,TV Show,Zindagi Gulzar Hai,Pakistan,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."